import LegalLayout from "../components/layout/LegalLayout.jsx";

const S = ({ title, children }) => (
  <section>
    <h2 className="text-xl font-bold text-white">{title}</h2>
    <div className="mt-3 space-y-3 text-sm leading-relaxed">{children}</div>
  </section>
);

export default function Terms() {
  return (
    <LegalLayout title="Terms of Service" updated="Draft — pending legal review">
      <p className="text-sm leading-relaxed">
        This is a plain-English draft prepared for Beeyond LLC's internal review. It is not final
        and has not been reviewed by an attorney. Do not treat it as a finished legal document.
      </p>

      <S title="1. Who we are">
        <p>
          Beeyond Vault is operated by Beeyond LLC, a sub-brand of Beeyond Estimators
          (beeyondestimators.com). These Terms govern your access to and use of the Beeyond Vault
          web application (the "Service").
        </p>
      </S>

      <S title="2. What the Service is — and isn't">
        <p>
          Beeyond Vault is a reference and document-preparation tool for contractors. It helps you
          look up commonly missed estimate line items, organize your own claims, and generate
          letters describing your own scope of work and pricing.
        </p>
        <p>
          Beeyond Vault does <strong className="text-white">not</strong> adjust insurance claims,
          represent policyholders, negotiate settlements, or provide public adjusting services of
          any kind. It does not provide legal advice. Florida Statute 626.854 governs public
          adjusting, and nothing in this Service is intended to constitute or substitute for that
          licensed activity.
        </p>
        <p>
          All code citations, item descriptions, and price ranges in the Vault are reference
          information only. You are responsible for verifying current code requirements and for
          confirming your own pricing before submitting anything to a carrier, client, or any
          third party.
        </p>
      </S>

      <S title="3. Accounts">
        <p>
          You must provide accurate account information and keep your login secure. You're
          responsible for all activity under your account. Crew plan accounts may add up to the
          number of seats included in that plan; the account owner is responsible for all seats
          on the subscription.
        </p>
      </S>

      <S title="4. Subscriptions, trials &amp; billing">
        <p>
          Beeyond Vault is offered on a subscription basis (Solo or Crew, billed monthly or
          annually) through Stripe. New subscriptions include a 7-day free trial; a valid payment
          method is required to start the trial, and your card will be charged automatically when
          the trial ends unless you cancel first.
        </p>
        <p>
          Subscriptions renew automatically at the then-current price until canceled. You can
          cancel anytime from your account's billing page (Stripe Customer Portal); cancellation
          takes effect at the end of the current billing period. Fees are non-refundable except
          where required by law.
        </p>
      </S>

      <S title="5. Acceptable use">
        <p>You agree not to:</p>
        <ul className="list-disc space-y-1 pl-5">
          <li>Share your login or resell access to the Service outside your paid seats,</li>
          <li>
            Scrape, copy, or redistribute the Vault database or its contents outside normal use of
            the Service,
          </li>
          <li>
            Use letters or content generated by the Service to misrepresent that you are a
            licensed public adjuster or to represent a policyholder's interests, or
          </li>
          <li>Use the Service for any unlawful purpose.</li>
        </ul>
      </S>

      <S title="6. Content accuracy">
        <p>
          We work to keep Vault items, code citations, and price ranges current and accurate for
          South Florida, but codes change, county interpretations vary, and market pricing moves.
          The Service is provided "as is" with respect to this reference data. Always verify
          before you rely on it.
        </p>
      </S>

      <S title="7. Ownership">
        <p>
          Beeyond LLC owns the Service, the Vault database, and all templates and content we
          provide. You own the claim data you enter and the letters you generate from it.
        </p>
      </S>

      <S title="8. Termination">
        <p>
          You may cancel your subscription at any time. We may suspend or terminate accounts that
          violate these Terms or that we reasonably believe are being used fraudulently or
          abusively.
        </p>
      </S>

      <S title="9. Limitation of liability">
        <p>
          The Service is a documentation aid. Beeyond LLC is not liable for claim outcomes,
          carrier decisions, code interpretations, or any damages arising from reliance on
          reference data in the Vault. To the maximum extent permitted by law, our total liability
          for any claim relating to the Service is limited to the amount you paid us in the 12
          months before the claim arose.
        </p>
      </S>

      <S title="10. Governing law">
        <p>These Terms are governed by the laws of the State of Florida.</p>
      </S>

      <S title="11. Changes">
        <p>
          We may update these Terms from time to time. Material changes will be communicated by
          email or in-app notice before they take effect.
        </p>
      </S>

      <S title="12. Contact">
        <p>
          Questions about these Terms:{" "}
          <a href="mailto:leads@beeyondestimators.com" className="text-gold-500 underline">
            leads@beeyondestimators.com
          </a>
        </p>
      </S>
    </LegalLayout>
  );
}
